language: python
python:
  - '3.6.7'
install: 
  - pip install -r requirements.txt
  - pip install coveralls
  
script: 
  - pytest --cov-report term-missing --cov app
  
after_success:
  - coveralls
  
cache: pip